[project]
name = "mcp-client"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "click>=8.1.8",
    "langchain>=0.3.20",
    "langchain-mcp-adapters>=0.0.3",
    "langchain-openai>=0.3.8",
    "langgraph>=0.3.7",
]
